### ISSUE TITLE
Shift step titles to function arguments

### ISSUE THREAD

**Issue by jhofman** [seankross/datamations#2]
Can we move allow titles that accompany each step to be passed as optional function arguments (e.g., "Each dot shows ...")?

**Comment by seankross** [comment]
This is implemented now for tibble datamations.

**Comment by jhofman** [comment]
Awesome.

@xiaoyingpu, any hope you can do the same for sanddance style?

**Comment by xiaoyingpu** [comment]
I'm working on it right now
